---
abstract: 'encrypt/decrypt file in Padre'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Crypt::Blowfish: 0
  Crypt::CBC: 0
  Locale::Msgfmt: 0.14
  Padre: 0.57
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Encrypt
provides:
  Padre::Plugin::Encrypt:
    file: lib/Padre/Plugin/Encrypt.pm
    version: 0.07
requires:
  File::ShareDir: 1.00
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Encrypt/
version: 0.07
